#ifndef ROBOT_MAP_H
#define ROBOT_MAP_H

#define DRIVE_XMSN_SHIFTER_ID 99 // 0

#define FR_DRIVE_MOTOR_ID 93 // 3
#define BR_DRIVE_MOTOR_ID 97 // 7
#define BL_DRIVE_MOTOR_ID 95 // 5
#define FL_DRIVE_MOTOR_ID 91 // 1

#define FR_STEER_MOTOR_ID 94 // 4
#define BR_STEER_MOTOR_ID 98 // 8
#define BL_STEER_MOTOR_ID 96 // 6
#define FL_STEER_MOTOR_ID 92 // 2

#define DRIVER_XBOX_CONTROLLER_ID 0
#define OPERATOR_XBOX_CONTROLLER_ID 1

#define LINE_FOLLOWER_MOTOR_ID 20

#define MASTER_ELEVATOR 89
#define SLAVE_ELEVATOR 100
#define ELEVATOR_SLIDE_SOLENOID 101

#define TOOL_CHANGER 201

#define CARGO_INTAKE_MOTOR 90
#define CARGO_INTAKE_SOLENOID 88

#endif // ROBOT_MAP_H
